# The URL the site will be built for
base_url = "https://diegovsky.dev"
theme = "tabi"
title = "Diego Augusto"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
minify_html = true

default_language = "en"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[[taxonomies]]
name = "tags"
feed = true

[languages.pt-BR]
title = "Diego Augusto"
generate_feeds = true

[[languages.pt-BR.taxonomies]]
name = "tags"
feed = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
skin = "evangelion"
show_reading_time = false
stylesheets = ["custom.css"]

[[extra.socials]]
name = "github"
url = "https://github.com/Diegovsky"
icon = "github"

[[extra.socials]]
name = "email"
url = "mailto:diegovsky.dev@gmail.com"
icon = "email"

[[extra.menu]]
name = "Projects"
url = "projects"
trailing_slash=true

# Put all your custom variables here
